### ISSUE TITLE
When watermark text using Chinese, it has an exception

### ISSUE THREAD

**Issue by yaoper** [Stirling-Tools/Stirling-PDF#1006]
Hello,
I am currently running this project using a Docker image.
But, when I try to add a Chinese watermark, it throws an exception.
How can I solve the issue?
Thanks!

![20240331-231910](https://github.com/Stirling-Tools/Stirling-PDF/assets/2835114/bbbe5854-6e1f-477d-99b8-cb83c86e779d)

**Comment by Frooodle** [comment]
Change alphabet away from roman

**Comment by yaoper** [comment]
Oh, it worked.

**Comment by eric-gitta-moore** [comment]
+1

```
❯ ~/Library/Java/JavaVirtualMachines/temurin-23.0.1/Contents/Home/bin/java -jar /Users/user/Downloads/Stirling-PDF.jar
01:02:46.169 [main] WARN  s.software.SPDF.SPdfApplication - External configuration file 'configs/settings.yml' does not exist.
01:02:46.169 [main] WARN  s.software.SPDF.SPdfApplication - Custom configuration file 'configs/custom_settings.yml' does not exist.
 ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____
/ ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
\___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_
 ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|
|____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|
Powered by Spring Boot 3.3.4
01:02:46.394 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.30.1 using Java 23.0.1 with PID 29825 (/Users/user/Downloads/Stirling-PDF.jar started by user in /Users/user)
01:02:46.395 [main] INFO  s.software.SPDF.SPdfApplication - The following 1 profile is active: "default"
...
Caused by: java.lang.IllegalArgumentException: No glyph for U+5927 (大) in font NotoSans-Regular
        at org.apache.pdfbox.pdmodel.font.PDCIDFontType2.encode(PDCIDFontType2.java:401)
        at org.apache.pdfbox.pdmodel.font.PDType0Font.encode(PDType0Font.java:476)
        at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:337)
        at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:368)
        at stirling.software.SPDF.controller.api.security.WatermarkController.addTextWatermark(WatermarkController.java:182)
        at stirling.software.SPDF.controller.api.security.WatermarkController.addWatermark(WatermarkController.java:91)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        ... 51 common frames omitted
```
