### ISSUE TITLE
PDF to html

### ISSUE THREAD

**Issue by willieramosjr1** [Stirling-Tools/Stirling-PDF#1064]
I keep getting an error when trying to convert to html, running version 0.22.8 on docker compose. 

**Compose file:**
```
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    volumes:
      - /home/user/stirling-pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /home/user/stirling-pdf/extraConfigs:/configs
      - /home/user/stirling-pdf/customFiles:/customFiles
      - /home/user/stirling-pdf/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLELOGIN=false
      - SYSTEM_MAXFILESIZE=150
      - METRICS_ENABLED=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
    restart: unless-stopped
```

**Stack Trace:**
```
org.springframework.web.servlet.resource.NoResourceFoundException: No static resource api/v1/convert/pdf/html.
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:585)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
```

I've been using stirling pdf for about 2 weeks now on a VPS and the same issue happened running it on a local machine. Not sure what else to do but I'd love to find a fix for it because it's one of the main reasons I need stirling pdf.

Not sure what version of docker compose i'm running because when i put the version in my yaml it says version is no longer supported or something.

**Comment by Frooodle** [comment]
Fixed in coming release, should be out later today :)
