### ISSUE TITLE
Bug: oauth2 results in incorrect settings.yml

### ISSUE THREAD

**Issue by Ludy87** [Stirling-Tools/Stirling-PDF#1152]
An update to the main version for this, if the app is built with `./gradlew bootRun` and then started, the `settings.yml` becomes incorrect.

```
10:47:28.941 [restartedMain] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [stirling.software.SPDF.SPdfApplication]
10:47:29.001 [restartedMain] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [stirling.software.SPDF.SPdfApplication]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:179)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:416)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) 
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 6, column 3:
      enableLogin: true # set to 'true ...
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 11, column 5:
        enabled: true # 'true' to enable ...
        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:515)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:135)
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:115)
        at stirling.software.SPDF.config.YamlPropertySourceFactory.createPropertySource(YamlPropertySourceFactory.java:20)
        at org.springframework.core.io.support.PropertySourceProcessor.processPropertySource(PropertySourceProcessor.java:92)
        at org.springframework.context.annotation.PropertySourceRegistry.processPropertySource(PropertySourceRegistry.java:75)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:281)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:314)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:197)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:165)
        ... 16 common frames omitted
```

When you start after the update, the block is added:

```yml
   #oauth2:
     enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable
   # issuer: "" # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) end-point
   # clientId: "" # Client ID from your provider
   # clientSecret: "" # Client Secret from your provider
   # autoCreateUser: false # set to 'true' to allow auto-creation of non-existing users
```

enabled should be commented out, but it isn't.

**Comment by Ludy87** [comment]
I didn't read the issues properly, sorry.
