### ISSUE TITLE
 I have to delete the config file manually before I run Stirling-PDF.exe every time. 

### ISSUE THREAD

**Issue by huouer** [Stirling-Tools/Stirling-PDF#1327]
It has started happening since 0.24.4 to my windows 11 even I'm admin.

**Comment by huouer** [comment]
____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____
/ ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
\___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_
 ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|
|____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|
Powered by Spring Boot 3.2.4
11:19:00.282 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: Failed to initialize application configuration
        at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:24)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:400)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
        at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.nio.file.FileSystemNotFoundException: null
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:173)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:159)
        at java.base/java.nio.file.Path.of(Path.java:208)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at stirling.software.SPDF.config.ConfigInitializer.ensureConfigExists(ConfigInitializer.java:49)
        at stirling.software.SPDF.config.ConfigInitializer.initialize(ConfigInitializer.java:22)
        ... 11 common frames omitted

**Comment by Frooodle** [comment]
should be fixed in 0.25.1 if you can try

**Comment by huouer** [comment]
all good now
