### ISSUE TITLE
"request" is null for Markdown to PDF

### ISSUE THREAD

**Issue by smfelsher** [Stirling-Tools/Stirling-PDF#1381]
I am running the full image of Stirling-PDF in a Docker container, using a simple Markdown file as an example.

```
# Heading 1

Some text.
```

I get the following stack trace when I use the **Markdown to PDF** tool with the above Markdown file.

```
java.lang.NullPointerException: Cannot invoke "stirling.software.SPDF.model.api.converters.HTMLToPdfRequest.getZoom()" because "request" is null
	at stirling.software.SPDF.utils.FileToPdf.convertHtmlToPdf(FileToPdf.java:56)
	at stirling.software.SPDF.controller.api.converters.ConvertMarkdownToPdf.markdownToPdf(ConvertMarkdownToPdf.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:925)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:62)
```

For reference, here is my `docker-compose.yaml`

```
name: stirling-pdf

services:
  stirling-pdf:
    image: frooodle/s-pdf:0.25.1
    container_name: stirling-pdf
    # No need to export ports since this will reside behind a reverse-proxy.
    # ports:
    #   - "8080:8080"
    environment:
      # Disable login feature.
      - DOCKER_ENABLE_SECURITY=false
      # Download calibre to enable PDF to/from book and advanced HTML
      # conversion. 
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=en_US
    volumes:
      - ./configs:/configs

networks:
  default:
    name: stirling-pdf-network
```

Any help would be greatly appreciated.

**Comment by smfelsher** [comment]
@Frooodle I see that you committed some fixes, so I downloaded `frooodle/s-pdf:alpha` and tried **Markdown to PDF** and it was successful this time.

I'm going to test some of my other Markdown files.

Thank you for the updates!

**Comment by Frooodle** [comment]
In latest release now :)
