### ISSUE TITLE
FAQ: "unable to register monitoring" on Synology

### ISSUE THREAD

**Issue by mpstein** [Stirling-Tools/Stirling-PDF#1728]
This issue is being submitted and then closed so that others can benefit from my suffering.

Installation model: Docker
Platform: Synology NAS

Error from logs: 
```
WARN s.s.S.u.FileMonitor [scheduling-1] not monitoring any directory, even the root directory itself: ./pipeline/watchedFolders
ERROR s.s.S.u.FileMonitor [scheduling-1] unable to register monitoring
java.io.IOException: User limit of inotify watches reached
        at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:257)
        at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
        at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:357)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

Solution:
This is caused due to the Synology's low default amount for max_user_watches. Based on the documentation from [SyncThing](https://forum.syncthing.net/t/setting-inotify-limit-permanently-on-synology-diskstation/12221/4), the following instructions were provided by [Zeuhl on Reddit.](https://www.reddit.com/r/jellyfin/comments/ntis6u/inotify_limit_in_docker_container/h0ufhhj/)

```
Go to Control Panel > Task Scheduler.
Create a New Task > Triggered Task > User-defined script.
In General Settings tab: give it a name (e.g. “sysctl inotify fix”) and Event = Boot-up.
In the Task Settings tab: enter this in the Run Command box:

sh -c '(sleep 90 && echo 204800 > /proc/sys/fs/inotify/max_user_watches)&'
```

**Comment by mpstein** [comment]
Closing issue to serve as FAQ per Froodle's recommendation in Discord.
