### ISSUE TITLE
[Bug]: I can't extract images due to Internal Server Error:jakarta.servlet.ServletException: Request processing failed: java.util.concurrent.ExecutionException: java.io.IOException: ICCBased colorspace array must have a stream as second element

### ISSUE THREAD

**Issue by NickAlexx** [Stirling-Tools/Stirling-PDF#1917]
### Installation Method

Local Installation

### The Problem

I wanted to extract the images from this pdf: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9116652/pdf/pbio.3001540.pdf

This is the stack trace:

java.util.concurrent.ExecutionException: java.io.IOException: ICCBased colorspace array must have a stream as second element

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)

	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)

	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.extractImages(ExtractImagesController.java:114)

	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)

	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)

	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)

	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)

	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)

	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)

	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)

	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)

	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)

	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)

	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)

	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:46)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)

	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)

	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)

	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)

	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)

	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)

	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)

	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)

	at org.eclipse.jetty.server.Server.handle(Server.java:181)

	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)

	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)

	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)

	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)

	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)

	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)

	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)

	at java.base/java.lang.Thread.run(Thread.java:1570)

Caused by: java.io.IOException: ICCBased colorspace array must have a stream as second element

	at org.apache.pdfbox.pdmodel.graphics.color.PDICCBased.checkArray(PDICCBased.java:142)

	at org.apache.pdfbox.pdmodel.graphics.color.PDICCBased.create(PDICCBased.java:110)

	at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:196)

	at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:74)

	at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.createFromCOSObject(PDColorSpace.java:257)

	at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:96)

	at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:74)

	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getColorSpace(PDImageXObject.java:862)

	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:187)

	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:477)

	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:438)

	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.extractImagesFromPage(ExtractImagesController.java:170)

	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.lambda$extractImages$0(ExtractImagesController.java:98)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

	... 1 more

### Version of Stirling-PDF

0.29.0

### Last Working Version of Stirling-PDF

http://localhost:8080/extract-images

### Browsers Affected

Firefox

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by sadi10** [comment]
I want to work on it.Please assign.

**Comment by sadi10** [comment]
The issue is solved now.
