### ISSUE TITLE
[Bug]: Compress page is empty

### ISSUE THREAD

**Issue by ektorasdj** [Stirling-Tools/Stirling-PDF#2137]
### Installation Method

Docker

### The Problem

Hello!
Thank you for this great tool.
In the latest 0.31.0 update, the compress page is empty.
![image](https://github.com/user-attachments/assets/d0972a28-c01c-47ba-89dc-edbf416b3881)

Thank you

### Version of Stirling-PDF

0.31.0

### Last Working Version of Stirling-PDF

0.30.1

### Page Where the Problem Occurred

http://localhost:7890/compress-pdf

### Browsers Affected

Firefox, Chrome, Safari, Microsoft Edge, Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by ektorasdj** [comment]
Hello! I am using the full edition (1.7gb image size) 
Thank you

**Comment by RMI78** [comment]
@ektorasdj You are not alone, same here using the dockerized version of the full container. 

I can provide a few logs from the docker container if it can help:
```
stirling-pdf         | 23:56:49.345 [qtp1215025252-64] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][qtp1215025252-64] Exception processing template "misc/compress-pdf": Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "misc/compress-pdf" - line 23, col 35)
stirling-pdf         | org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "misc/compress-pdf" - line 23, col 35)
stirling-pdf         |  at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292)
stirling-pdf         |  at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166)
stirling-pdf         |  at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
stirling-pdf         |  at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
stirling-pdf         |  at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
stirling-pdf         |  at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144)
stirling-pdf         |  at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
stirling-pdf         |  at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
stirling-pdf         |  at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
stirling-pdf         |  at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:918)
stirling-pdf         |  at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228)
stirling-pdf         |  at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
stirling-pdf         |  at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592)
stirling-pdf         |  at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
stirling-pdf         |  at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
stirling-pdf         |  at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
stirling-pdf         |  at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1432)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1168)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
stirling-pdf         |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
stirling-pdf         |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
stirling-pdf         |  at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:48)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
stirling-pdf         |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
stirling-pdf         |  at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
stirling-pdf         |  at org.eclipse.jetty.server.Server.handle(Server.java:182)
stirling-pdf         |  at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
stirling-pdf         |  at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
stirling-pdf         |  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
stirling-pdf         |  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
stirling-pdf         |  at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
stirling-pdf         |  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
stirling-pdf         |  at java.base/java.lang.Thread.run(Thread.java:1583)
stirling-pdf         | Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'parameterName' cannot be found on null
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:225)
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:112)
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorValueRef.getValue(PropertyOrFieldReference.java:417)
stirling-pdf         |  at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:97)
stirling-pdf         |  at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:114)
stirling-pdf         |  at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338)
stirling-pdf         |  at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265)
stirling-pdf         |  ... 72 common frames omitted
stirling-pdf         | 23:56:49.346 [qtp1215025252-64] WARN  o.e.j.ee10.servlet.ServletChannel - /compress-pdf
stirling-pdf         | jakarta.servlet.ServletException: Request processing failed: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "misc/compress-pdf" - line 23, col 35)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1022)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
stirling-pdf         |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
stirling-pdf         |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
stirling-pdf         |  at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:48)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
stirling-pdf         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
stirling-pdf         |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
stirling-pdf         |  at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
stirling-pdf         |  at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
stirling-pdf         |  at org.eclipse.jetty.server.Server.handle(Server.java:182)
stirling-pdf         |  at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
stirling-pdf         |  at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
stirling-pdf         |  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
stirling-pdf         |  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
stirling-pdf         |  at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
stirling-pdf         |  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
stirling-pdf         |  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
stirling-pdf         |  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
stirling-pdf         |  at java.base/java.lang.Thread.run(Thread.java:1583)
stirling-pdf         | Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "misc/compress-pdf" - line 23, col 35)
stirling-pdf         |  at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292)
stirling-pdf         |  at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166)
stirling-pdf         |  at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
stirling-pdf         |  at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
stirling-pdf         |  at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
stirling-pdf         |  at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144)
stirling-pdf         |  at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
stirling-pdf         |  at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
stirling-pdf         |  at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
stirling-pdf         |  at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:918)
stirling-pdf         |  at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228)
stirling-pdf         |  at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
stirling-pdf         |  at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592)
stirling-pdf         |  at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
stirling-pdf         |  at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077)
stirling-pdf         |  at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372)
stirling-pdf         |  at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1432)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1168)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106)
stirling-pdf         |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
stirling-pdf         |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
stirling-pdf         |  ... 51 common frames omitted
stirling-pdf         | Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'parameterName' cannot be found on null
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:225)
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:112)
stirling-pdf         |  at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorValueRef.getValue(PropertyOrFieldReference.java:417)
stirling-pdf         |  at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:97)
stirling-pdf         |  at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:114)
stirling-pdf         |  at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338)
stirling-pdf         |  at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265)
stirling-pdf         |  ... 72 common frames omitted
```

This is my very first time setting up Stirling on my stack, I am using the same version 0.31.0, I can't tell if it was the case on version 0.30.0. I have the same image and my docker compose is barrely the same as the one provided in the README.

**Comment by Frooodle** [comment]
Those logs greatly help thanks for that 
You should be good using the previous version for now issue was introduced in 0.31.0 
Will hotfix this tomorrow morning

**Comment by Jackie264** [comment]
Me too
<img width="1436" alt="Screenshot 2024-10-31 at 11 25 03" src="https://github.com/user-attachments/assets/f9b49aaa-49f8-4ec7-b458-e2c69c57f304">
[_stirling-pdf_logs.txt](https://github.com/user-attachments/files/17581449/_stirling-pdf_logs.txt)
