### ISSUE TITLE
[Bug]: Null submit button for PDF to CSV conversion

### ISSUE THREAD

**Issue by omar-ahmed42** [Stirling-Tools/Stirling-PDF#2319]
### Installation Method

Local Installation

### The Problem

# Description:

Submitting a PDF for conversion to CSV results in an exception being thrown in the frontend (in the console) thus not sending a request to the backend for conversion.

## Steps to reproduce:
1. Upload a PDF file.
2. Click "Extract" button (Submit form)
3. Check Web console

### Firefox's error message:
```
Uncaught (in promise) TypeError: submitButton is null
    <anonymous> /js/downloader.js:39
    jQuery 2
2 downloader.js:39:34
    <anonymous> /js/downloader.js:39
    jQuery 2
```

### Microsoft Edge's error message:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at HTMLFormElement.<anonymous> (downloader.js:39:47)
    at HTMLFormElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

### Screenshot from Microsoft Edge:

![error](https://github.com/user-attachments/assets/b5e0ed72-d8db-4887-ad20-5c948e978f0e)

_Note: Docker alpha version is also affected by this_

### Version of Stirling-PDF

0.33.2

### Last Working Version of Stirling-PDF

0.33.1

### Page Where the Problem Occurred

/pdf-to-csv

### Relevant Log Output

```txt
Error message: Uncaught (in promise) TypeError: submitButton is null
File: /js/downloader.js line 39
```

### Browsers Affected

Firefox, Microsoft Edge

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by omar-ahmed42** [comment]
I feel like this might be a **_good first issue_**
