### ISSUE TITLE
Issues with PDF to Image 

### ISSUE THREAD

**Issue by astronyu** [Stirling-Tools/Stirling-PDF#494]
I tried to convert a pdf with multiple pages of scanned images into individual images. It does generate numbers of individual images but some of them does not have image in it. Attached is one of the pdf sample I used.
[Expense Receipt (Jul11).pdf](https://github.com/Frooodle/Stirling-PDF/files/13545793/Expense.Receipt.Jul11.pdf)

The logs shows this which I suspect the cause of the issue however I do not know how to fix it.
`[nio-8080-exec-1] o.a.p.contentstream.PDFStreamEngine      : Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed`

**Comment by Frooodle** [comment]
Try now

**Comment by astronyu** [comment]
> Try now

You're awesome! It works now :)

**Comment by Frooodle** [comment]
Sorry having to remove this, the licensing for jpeg2000 is not usable for us as a opensource application

**Comment by smeredith** [comment]
Can you make instructions on how me might add this to the docker image ourselves?

**Comment by janaxhell** [comment]
I have just deployed the :latest build 0.28.1, nevertheless if I try to extract images from a PDF I get this error:

```
java.util.concurrent.ExecutionException: org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.extractImages(ExtractImagesController.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:61)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:858)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
	at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:172)
	at org.apache.pdfbox.filter.JPXFilter.readJPX(JPXFilter.java:123)
	at org.apache.pdfbox.filter.JPXFilter.decode(JPXFilter.java:72)
	at org.apache.pdfbox.filter.Filter.decode(Filter.java:254)
	at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:73)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:172)
	at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:193)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.createInputStream(PDImageXObject.java:895)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.from8bit(SampledImageReader.java:469)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:217)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:477)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:438)
	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.extractImagesFromPage(ExtractImagesController.java:154)
	at stirling.software.SPDF.controller.api.misc.ExtractImagesController.lambda$extractImages$0(ExtractImagesController.java:94)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
```

**Comment by janaxhell** [comment]
0.28.2 works fine, but output images are numbered in an inconsistent way:
if I extract to PNG, they are sorted in a certain order, if in JPG, in another and besides that the numbers are not padded to the same amount of cyphens, making it very hard to clean and reorganize. Is it possible to fix/set this? IMO the "Copy_123456789" string is completely redundant.

PDF extracted to PNG:

```
Glow #5 Digital - Copy_1122768146 (Page 15).png
Glow #5 Digital - Copy_1138997403 (Page 11).png
Glow #5 Digital - Copy_1183707749 (Page 26).png
Glow #5 Digital - Copy_1188016225 (Page 16).png
Glow #5 Digital - Copy_1212935413 (Page 7).png
Glow #5 Digital - Copy_1240352832 (Page 17).png
Glow #5 Digital - Copy_1265028173 (Page 37).png
Glow #5 Digital - Copy_1327181887 (Page 38).png
Glow #5 Digital - Copy_1333343403 (Page 5).png
Glow #5 Digital - Copy_1383876122 (Page 27).png
Glow #5 Digital - Copy_141265006 (Page 1).png
Glow #5 Digital - Copy_1450472296 (Page 22).png
Glow #5 Digital - Copy_1598195969 (Page 24).png
Glow #5 Digital - Copy_1707628589 (Page 1).png
Glow #5 Digital - Copy_1733685968 (Page 29).png
Glow #5 Digital - Copy_1756631982 (Page 25).png
Glow #5 Digital - Copy_1869632053 (Page 18).png
Glow #5 Digital - Copy_1892356604 (Page 6).png
Glow #5 Digital - Copy_1894483808 (Page 36).png
Glow #5 Digital - Copy_1907282805 (Page 10).png
Glow #5 Digital - Copy_1915738626 (Page 8).png
Glow #5 Digital - Copy_1931586631 (Page 38).png
Glow #5 Digital - Copy_1943664271 (Page 12).png
Glow #5 Digital - Copy_1976904858 (Page 30).png
Glow #5 Digital - Copy_2076899389 (Page 20).png
Glow #5 Digital - Copy_2078566038 (Page 31).png
Glow #5 Digital - Copy_224044505 (Page 33).png
Glow #5 Digital - Copy_256778840 (Page 35).png
Glow #5 Digital - Copy_25824733 (Page 28).png
Glow #5 Digital - Copy_265798899 (Page 14).png
Glow #5 Digital - Copy_279463216 (Page 3).png
Glow #5 Digital - Copy_313415062 (Page 3).png
Glow #5 Digital - Copy_319442419 (Page 21).png
Glow #5 Digital - Copy_407424096 (Page 19).png
Glow #5 Digital - Copy_417045647 (Page 32).png
Glow #5 Digital - Copy_449648363 (Page 9).png
Glow #5 Digital - Copy_538601603 (Page 13).png
Glow #5 Digital - Copy_617743020 (Page 3).png
Glow #5 Digital - Copy_656058615 (Page 23).png
Glow #5 Digital - Copy_867613570 (Page 36).png
Glow #5 Digital - Copy_889521716 (Page 34).png
Glow #5 Digital - Copy_906245822 (Page 2).png
```

The same PDF extracted to JPG, page numbers are completely scrambled:

```
Glow #5 Digital - Copy_1149820255 (Page 28).jpg
Glow #5 Digital - Copy_1177823445 (Page 24).jpg
Glow #5 Digital - Copy_1215432815 (Page 23).jpg
Glow #5 Digital - Copy_125144217 (Page 31).jpg
Glow #5 Digital - Copy_1371241509 (Page 3).jpg
Glow #5 Digital - Copy_1389042179 (Page 20).jpg
Glow #5 Digital - Copy_1421879920 (Page 36).jpg
Glow #5 Digital - Copy_1498391470 (Page 33).jpg
Glow #5 Digital - Copy_1587325266 (Page 36).jpg
Glow #5 Digital - Copy_1705715712 (Page 35).jpg
Glow #5 Digital - Copy_1746361491 (Page 25).jpg
Glow #5 Digital - Copy_179852127 (Page 19).jpg
Glow #5 Digital - Copy_1806688335 (Page 17).jpg
Glow #5 Digital - Copy_184494292 (Page 1).jpg
Glow #5 Digital - Copy_1890158929 (Page 3).jpg
Glow #5 Digital - Copy_198696829 (Page 7).jpg
Glow #5 Digital - Copy_1987542339 (Page 3).jpg
Glow #5 Digital - Copy_2023333338 (Page 34).jpg
Glow #5 Digital - Copy_2023665096 (Page 22).jpg
Glow #5 Digital - Copy_2083068949 (Page 15).jpg
Glow #5 Digital - Copy_208453813 (Page 8).jpg
Glow #5 Digital - Copy_210055332 (Page 26).jpg
Glow #5 Digital - Copy_2103445928 (Page 10).jpg
Glow #5 Digital - Copy_233379146 (Page 27).jpg
Glow #5 Digital - Copy_246958017 (Page 9).jpg
Glow #5 Digital - Copy_247339910 (Page 16).jpg
Glow #5 Digital - Copy_258379865 (Page 13).jpg
Glow #5 Digital - Copy_303168978 (Page 6).jpg
Glow #5 Digital - Copy_328235692 (Page 2).jpg
Glow #5 Digital - Copy_401685369 (Page 38).jpg
Glow #5 Digital - Copy_472622177 (Page 37).jpg
Glow #5 Digital - Copy_485792859 (Page 18).jpg
Glow #5 Digital - Copy_555777525 (Page 30).jpg
Glow #5 Digital - Copy_563098605 (Page 11).jpg
Glow #5 Digital - Copy_579179811 (Page 14).jpg
Glow #5 Digital - Copy_595023359 (Page 38).jpg
Glow #5 Digital - Copy_625161197 (Page 21).jpg
Glow #5 Digital - Copy_645968128 (Page 32).jpg
Glow #5 Digital - Copy_737009056 (Page 1).jpg
Glow #5 Digital - Copy_737445315 (Page 12).jpg
Glow #5 Digital - Copy_763246017 (Page 5).jpg
Glow #5 Digital - Copy_965281238 (Page 29).jpg
```

**Comment by Frooodle** [comment]
Yeah I can get this fixed for next patch

**Comment by janaxhell** [comment]
Mmm, seems you forgot. ;-)

**Comment by Frooodle** [comment]
... Ah... You are exactly right 😂

**Comment by Frooodle** [comment]
I didn't reopen as it was different issue
.
 so forgot all about it
