### ISSUE TITLE
Split 300MB PDF File

### ISSUE THREAD

**Issue by Crosus97** [Stirling-Tools/Stirling-PDF#742]
Hi, 

First: i know that is a huge file but im trying to use it

Second the error generated is this:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/46854222/d4fcd765-3f12-48f7-8fc8-46756fca7511)

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at org.apache.pdfbox.pdfwriter.COSStandardOutputStream.write(COSStandardOutputStream.java:129)
	at org.apache.pdfbox.io.IOUtils.copy(IOUtils.java:70)
	at org.apache.pdfbox.pdfwriter.COSWriter.visitFromStream(COSWriter.java:1289)
	at org.apache.pdfbox.cos.COSStream.accept(COSStream.java:416)
	at org.apache.pdfbox.cos.COSObject.accept(COSObject.java:187)
	at org.apache.pdfbox.pdfwriter.COSWriter.doWriteObject(COSWriter.java:570)
	at org.apache.pdfbox.pdfwriter.COSWriter.doWriteObjects(COSWriter.java:496)
	at org.apache.pdfbox.pdfwriter.COSWriter.doWriteBody(COSWriter.java:480)
	at org.apache.pdfbox.pdfwriter.COSWriter.visitFromDocument(COSWriter.java:1182)
	at org.apache.pdfbox.cos.COSDocument.accept(COSDocument.java:452)
	at org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1455)
	at org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1342)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1380)
	at stirling.software.SPDF.controller.api.SplitPDFController.splitPdf(SplitPDFController.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	
	
	TY
	
	
	 [UPDATE]
	 Update After this fail, the docker shot up the memory

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/46854222/07e6b200-7c07-4fbe-907a-99b53ec29966)
and i need to restart it

**Comment by Crosus97** [comment]
Update After this fail, the docker shot up the memory

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/46854222/07e6b200-7c07-4fbe-907a-99b53ec29966)
and i need to restart it

**Comment by Frooodle** [comment]
To confirm 
Is your intent of 1-331 to create 331 documents each 1 page long?

**Comment by Crosus97** [comment]
yep, its a entrance PDF in every page is a entrance

**Comment by Crosus97** [comment]
you need any more information?

**Comment by sbplat** [comment]
Not at the moment. I haven't tried reproducing the issue yet.

**Comment by Frooodle** [comment]
Cant reproduce with any reasonable sized document (1GB one doesnt do insane memory usage etc)
