### ISSUE TITLE
Program exited with error

### ISSUE THREAD

**Issue by TimothyYe** [Stirling-Tools/Stirling-PDF#747]
The docker container exited with the `IllegalArgumentException`:

```
08:58:09.752 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
08:58:09.753 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
08:58:09.754 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 1 ms
11:21:33.715 [http-nio-8080-exec-15] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x00{0x010x000x00w0x030x030xa80xf00x08M[A0x0d0xb9)0x8ci0x910x130xea.9P0xd6A~ng0xfa0x9b`s0xb8S0xaf0xcd0x040x170x000x000x1a0xc0/0xc0+0xc00x110xc00x070xc00x130xc00x090xc00x140xc00x0a0x000x050x00/0x0050xc00x120x000x0a0x010x000x0040x000x050x000x050x010x000x000x000x000x000x0a0x000x080x000x060x000x170x000x180x000x190x000x0b0x000x020x010x000x000x0d0x000x100x000x0e0x040x010x040x030x020x010x020x030x040x010x050x010x060x010xff0x010x000x010x00...]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)
14:22:58.863 [http-nio-8080-exec-22] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x010x010x000x010x000x080x000x000x000x010x000x000x000x000x000x000x010x040x000x010x010xc20x060x000x0e0x04REQUEST_METHODPOST0x0b0x12SCRIPT_NAME/usr/bin/phar.phar0x110x0bGATEWAY_INTERFACEFastCGI/1.00x0f0x12SCRIPT_FILENAME/usr/bin/phar.phar0x0f0x0eSERVER_SOFTWAREphp/fcgiclient0x0b0x04REMOTE_PORT99850x0b0x09SERVER_ADDR127.0.0.10x0f0x08SERVER_PROTOCOLHTTP/1.10x0d0x01DOCUMENT_ROOT/0x0b0x09REMOTE_ADDR127.0.0.10x0b0x02SERVER_PORT800x0e0x02CONTENT_LENGTH520x094PHP_VALUEauto_prepend_file ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)
23:43:58.429 [http-nio-8080-exec-16] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: No acceptable representation]
16:40:39.877 [http-nio-8080-exec-10] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xee0x010x000x000xea0x030x03Y0x9aT0xb20xa00xdbJ0xe5b\N0xe70x0cZK0xf30xd30x1eo0xf0I0xc60xaf{0xf30xe6I0xdf0xf10xf90x950xab ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by sbplat** [comment]
You're probably using http**s** instead of HTTP without an SSL certificate setup. This is likely the case if you're on localhost.

**Comment by sbplat** [comment]
@TimothyYe did this solve your issue?

**Comment by TimothyYe** [comment]
> You're probably using HTTP**S** instead of HTTP without an SSL certificate setup. This is likely the case if you're on localhost.

Yes, I run it via the docker container.
