### ISSUE TITLE
Unable to start Docker Container

### ISSUE THREAD

**Issue by Korunos47** [Stirling-Tools/Stirling-PDF#808]
Since the last alpha update on my unraid using the CA Template, I'm unable to start the container anymore.
Here is the Log:

``` 08:49:51.347 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 29, column 3:
      enabled: true # 'true' to enable ... 
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 30, column 5:
        installBookFormats: false # Inst ... 
        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162)
        at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:515)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
        at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
        at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
        at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
        at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
        at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
        at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
        at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
        at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:229)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
        at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
        at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:137)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
        at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ```

**Comment by Frooodle** [comment]
Which docker tag are you using?

But also it seems to be issue with settings.yml in config file 
You can try delete it

**Comment by Frooodle** [comment]
Could you send a copy of it over first

Then you can delete to unblock yourself

**Comment by Korunos47** [comment]
I can't attach it directly here, so here is the content of the settings.yml:

`# Welcome to settings file
# Remove comment marker # if on start of line to enable the configuration
# If you want to override with environment parameter follow parameter naming SECURITY_INITIALLOGIN_USERNAME

security:
  enableLogin: false # set to 'true' to enable login
  csrfDisabled: true
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts

system:

  defaultLocale: 'en-US' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # Set to enable functionality which might need more testing before it fully goes live (This feature might make no changes)
  customApplications:
    bookAndHtmlFormatsInstalled: false # Installs Calibre for book format conversion (For non docker it must be manually downloaded but will need to be true to show in UI)

#ui:
#  appName: exampleAppName # Application's visible name
#  homeDescription: I am a description # Short description or tagline shown on homepage.
#  appNameNavbar: navbarName # Name displayed on the navigation bar

endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable
    installBookFormats: false # Installs Calibre for book format conversion (For non docker it must be manually downloaded but will need to be true to show in UI)
    installAdvancedHtmlToPDF: false # DO NOT USE EXTERNALLY, NOT SAFE! Install wkHtmlToPDF (For non docker it must be manually downloaded but will need to be true to show in UI)
`

**Comment by Frooodle** [comment]
Thanks I see issue! :)

**Comment by Frooodle** [comment]
Last 2 lines should be deleted

**Comment by Korunos47** [comment]
Good to know! Thank you very much!

**Comment by soonic6** [comment]
> Last 2 lines should be deleted

i changed to :latest an uncomment the last two lines makes my container runable again.

**Comment by Frooodle** [comment]
> > Last 2 lines should be deleted
> 
> ~~i changed to :latest an uncomment the last two lines makes my container runable again.~~
> 
> oh wait, i was wrong:
> ```
> Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
>         at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
>         at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162)
>         at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:515)
>         at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
>         at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
>         at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:135)
>         at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:115)
>         at stirling.software.SPDF.config.YamlPropertySourceFactory.createPropertySource(YamlPropertySourceFactory.java:20)
>         at org.springframework.core.io.support.PropertySourceProcessor.processPropertySource(PropertySourceProcessor.java:92)
>         at org.springframework.context.annotation.PropertySourceRegistry.processPropertySource(PropertySourceRegistry.java:75)
>         at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:281)
>         at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246)
>         at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189)
>         at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:314)
>         at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246)
>         at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:197)
>         at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:165)
>         ... 18 common frames omitted
> Copying original files without overwriting existing files
> Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.20.2
> 19:52:05.762 [main] ERROR o.s.boot.SpringApplication - Application run failed
> org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
>  in 'reader', line 24, column 3:
>       enabled: true # 'true' to enable ... 
>       ^
> expected <block end>, but found '<block mapping start>'
>  in 'reader', line 25, column 5:
>         bookAndHtmlFormatsInstalled: fal ... 
>         ^
> 
>         at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654)
>         at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
>         at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
>         at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
>         at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
>         at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
>         at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
>         at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
>         at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
>         at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
>         at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
>         at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
>         at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:162)
>         at org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99)
>         at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:515)
>         at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:203)
>         at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:169)
>         at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
>         at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
>         at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
>         at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
>         at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:96)
>         at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
>         at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
>         at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
>         at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
>         at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:229)
>         at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
>         at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
>         at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
>         at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
>         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
>         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
>         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
>         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:137)
>         at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
>         at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
>         at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
>         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
>         at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
>         at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
>         at stirling.software.SPDF.SPdfApplication.main(SPdfApplication.java:58)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
>         at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
>         at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
> 
> ** Press ANY KEY to close this window ** 
> ```
> 
> 

If you delete whole file it should recreate as healthy version

**Comment by Frooodle** [comment]
Should be resolved now in alpha tag

**Comment by Joshndroid** [comment]
I had just noticed this issue as well.
I am wondering if you need to pin this issue for a bit of time so others can also jump to this without filling your issues up (i was about to make one but decided to check your closed issues to see if there was something similar before i did)
