### ISSUE TITLE
Internal Server Error:Process timeout exceeded.

### ISSUE THREAD

**Issue by maisen20** [Stirling-Tools/Stirling-PDF#917]
Hi and thank you all for this very nice application.

I have installed Stirling PDF via Docker, but unfortunately the compression does not work. For example, if I set Manual Mode to 4 and Automatic Mode to 9MB, I get the following error after a few minutes:

```
2024-03-14 10:08:55,230 INFO s.s.S.SPdfApplication [main] Starting SPdfApplication v0.22.2 using Java 17.0.10 with PID 7 (/app.jar started by root in /)
2024-03-14 10:08:55,235 INFO s.s.S.SPdfApplication [main] No active profile set, falling back to 1 default profile: "default"
2024-03-14 10:08:58,239 INFO o.s.b.w.e.t.TomcatWebServer [main] Tomcat initialized with port 8080 (http)
2024-03-14 10:08:58,259 INFO o.a.c.h.Http11NioProtocol [main] Initializing ProtocolHandler ["http-nio-8080"]
2024-03-14 10:08:58,263 INFO o.a.c.c.StandardService [main] Starting service [Tomcat]
2024-03-14 10:08:58,264 INFO o.a.c.c.StandardEngine [main] Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-14 10:08:58,347 INFO o.a.c.c.C.[.[.[/] [main] Initializing Spring embedded WebApplicationContext
2024-03-14 10:08:58,349 INFO o.s.b.w.s.c.ServletWebServerApplicationContext [main] Root WebApplicationContext: initialization completed in 2951 ms
2024-03-14 10:08:58,704 INFO s.s.S.SPdfApplication [main] Running configs ApplicationProperties [security=Security [enableLogin=false, initialLogin=null,  csrfDisabled=true], system=System [defaultLocale=de-DE, googlevisibility=false, rootURIPath=null, customStaticFilePath=null, maxFileSize=null, enableAlphaFunctionality=false], ui=null, endpoints=Endpoints [toRemove=[], groupsToRemove=[]], metrics=Metrics [enabled=true], automaticallyGenerated=null, autoPipeline=null]
2024-03-14 10:08:59,425 INFO s.s.S.c.EndpointConfiguration [main] Disabling pdf-to-book
2024-03-14 10:08:59,425 INFO s.s.S.c.EndpointConfiguration [main] Disabling book-to-pdf
2024-03-14 10:09:00,459 INFO o.s.b.a.e.w.EndpointLinksResolver [main] Exposing 1 endpoint(s) beneath base path '/actuator'
2024-03-14 10:09:00,540 INFO o.a.c.h.Http11NioProtocol [main] Starting ProtocolHandler ["http-nio-8080"]
2024-03-14 10:09:00,576 INFO o.s.b.w.e.t.TomcatWebServer [main] Tomcat started on port 8080 (http) with context path ''
2024-03-14 10:09:00,615 INFO s.s.S.SPdfApplication [main] Started SPdfApplication in 6.418 seconds (process running for 7.911)
2024-03-14 10:09:01,700 INFO s.s.S.SPdfApplication [main] Stirling-PDF Started.
2024-03-14 10:09:01,701 INFO s.s.S.SPdfApplication [main] Navigate to http://localhost:8080
2024-03-14 10:09:16,979 INFO o.a.c.c.C.[.[.[/] [http-nio-8080-exec-1] Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-03-14 10:09:16,980 INFO o.s.w.s.DispatcherServlet [http-nio-8080-exec-1] Initializing Servlet 'dispatcherServlet'
2024-03-14 10:09:16,982 INFO o.s.w.s.DispatcherServlet [http-nio-8080-exec-1] Completed initialization in 2 ms
2024-03-14 10:12:28,885 WARN o.a.p.p.g.c.PDICCBased [http-nio-8080-exec-1] ICC profile is Perceptual, ignoring, treating as Display class
2024-03-14 10:17:13,120 INFO s.s.S.u.ProcessExecutor [http-nio-8080-exec-4] Running command: gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=/tmp/output_9426542623407872068.pdf /tmp/input_11570097237970123580.pdf
2024-03-14 10:18:28,252 INFO s.s.S.u.ProcessExecutor [http-nio-8080-exec-4] Running command: gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=/tmp/output_9426542623407872068.pdf /tmp/input_11570097237970123580.pdf
2024-03-14 10:22:08,689 WARN o.a.p.p.g.c.PDICCBased [http-nio-8080-exec-11] ICC profile is Perceptual, ignoring, treating as Display class
2024-03-14 10:22:09,036 WARN o.a.p.p.g.c.PDICCBased [http-nio-8080-exec-11] ICC profile is Perceptual, ignoring, treating as Display class
2024-03-14 10:23:28,257 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] [http-nio-8080-exec-4] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.io.IOException: Process timeout exceeded.
  at stirling.software.SPDF.utils.ProcessExecutor.runCommandWithOutputHandling(ProcessExecutor.java:165)
  at stirling.software.SPDF.utils.ProcessExecutor.runCommandWithOutputHandling(ProcessExecutor.java:82)
  at stirling.software.SPDF.controller.api.misc.CompressController.optimizePdf(CompressController.java:128)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:261)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:189)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at stirling.software.SPDF.config.MetricsFilter.doFilterInternal(MetricsFilter.java:62)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:735)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:840)
```

I had also tried other settings, I also got a PDF after compressing but it was exactly the same size as the original PDF. The test PDF (56MB) has many large images (up to 8.5 MB per image) with high resolution (7000px x 3000 px).

Runs on a Synology NAS RS1221+

**Comment by maisen20** [comment]
I have now moved the container to another device and solved the "problem".
