### ISSUE TITLE
[Bug] Cannot read api schema in pipeline menu

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Stirling-Tools/Stirling-PDF#986]
```javascript
pipeline.js:303 Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at showpipelineSettingsModal (pipeline.js:303:54)
    at HTMLButtonElement.<anonymous> (pipeline.js:293:5)
```

**Comment by Frooodle** [comment]
Are you running any nginx layer or non default port? Any unique Auth etc?

**Comment by ZzzzzzzSkyward** [comment]
I'm running the latest exeversion in release in win10. I think it is just a bug? There is no apiDocs[operation].post.requestBody, you need to use apiDocs[operation].post.response instead.

**Comment by ZzzzzzzSkyward** [comment]
the post looks like
```javascript
{
    "tags": [
        "Misc"
    ],
    "summary": "Extract images from a PDF file",
    "description": "This endpoint extracts images from a given PDF file and returns them in a zip file. Users can specify the output image format. Input:PDF Output:IMAGE/ZIP Type:SIMO",
    "operationId": "extractImages",
    "parameters": [
        {
            "name": "request",
            "in": "query",
            "required": true,
            "schema": {
                "$ref": "#/components/schemas/PDFWithImageFormatRequest"
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "*/*": {
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "format": "byte"
                        }
                    }
                }
            }
        }
    }
}```
